### PR TITLE
Tries creating TMP directory if does not exist.

### PR DESCRIPTION
**Pull request by lamasgergo**
I think its a good feature if you dont have permissions to create directory, but the script has access. 
For example automatic deployment from git repository, which deletes all folders and files in TMP folder.

### CODE REVIEW

**Comment by lamasgergo** [comment]
Test case needed.

**Comment by mirko-pagliai** [comment]
Hello @lamasgergo . Thank you for your precious contribution.

I think this plugin should respect CakePHP standards. Look at the [CookBook](https://book.cakephp.org/3.0/en/installation.html#permissions), it says:
> Composer’s installation process makes tmp and its subfolders globally writeable to get things up and running quickly but you can update the permissions for better security and keep them writable only for the web server user.

In fact, in CakePHP directories are created [by the installer](https://github.com/cakephp/app/blob/master/src/Console/Installer.php#L97).

It's probably the case to do the same with this plugin. What do you think about it?

**Comment by lamasgergo** [comment]
Hello! Thank you for answer! Yes cake php creates some directories, but the if the tmp folder not exists, cake trying to create it. But its happening after bootstrap loading. So if you checking asset directory in bootstrap you will get error. In my case we have a git repository wich auto deploying without tmp folder, (because it's in git ignore). So this plugin always causes error on first run. I have to create folders by manual. Why not creating asset folder automatically? Thats why i sent a pull request. Im i wrong?

**Comment by mirko-pagliai** [comment]
> But its happening after bootstrap loading. So if you checking asset directory in bootstrap you will get error.

So, ok. We have to create the folders.

> Thats why i sent a pull request. Im i wrong?

No, you're right and contributions are always welcome! :-)

But, in my opinion, that code should still be in the bootstrap, obviously **before** it checks if the directory is writable.

If you put the code in the `asset()` method, this has some critical issues:
* if I need to generate more assets in the same request, that code will run multiple times
* If tomorrow I want to add another method that writes to the same directory, I should enter the code there too;
* etc etc

It seems to me even simpler:

```
$target = Configure::read('Assets.target');

if (!file_exists($target)) {
    @mkdir($target);
}

if (!is_writeable($target)) {
    trigger_error(sprintf('Directory %s not writeable', target), E_USER_ERROR);
}
```

(note: I don't need to check if the directory was created correctly from the function. Because in any case, I will check later if it is writable)

**Comment by lamasgergo** [comment]
Hi! Your shorter solution is ok!
And yes i'm thinking too, where is the best place for this directory checking.
I think you are wrong because bootstrap runs multiple times too, so the checking runs wherever you place this code :)
How about a config param check? 
I think some caching should be great for this, i will thinking on it. 
If i see well, you always checking filetime of all assets, so this plugin always makes a lot of file system readings. 
Any ideas? [markstory ' s](https://github.com/markstory/asset_compress) compress plugin creates generated assets with fixed name. so if its not available, the site will rendered without css :)

thats why i have chosen this plugin, its more flexible. And you dont need console, and more configuration files.
lets talk about this problem :) i think we will find a good solution for reduce file system actions.

**Comment by mirko-pagliai** [comment]
> I think you are wrong because bootstrap runs multiple times too

Are you sure? If in my layout:

```
echo $this->Asset->css(['first.css', 'second.css'];
echo $this->Asset->css('third.css');
echo $this->Asset->script('some_code.js');
```

are you sure the bootstrap will run 3 times?
Anyway, even so, at worst it's the same thing. However, besides this, in my opinion, what concerns the "preparation of the environment" should still be in the bootstrap.

> How about a config param check?
I think some caching should be great for this, i will thinking on it.

What do you mean? Save to cache the result of the check?
I'm pretty sure that would be worse, Especially if you use the cache file (as most users do).

> If i see well, you always checking filetime of all assets, so this plugin always makes a lot of file system readings.

Yes I know. This is the weakness of the plugin. Even reading the date of the last edit is not as expensive as reading the contents of a file. It's not very serious.
If there is a better way to update assets without user manual input, obviously I'm happy. I did not think of anything better.

**Comment by mirko-pagliai** [comment]
This plugin was created for very simple reasons.

**What I want**
1. asset files combined and minified;
2. an helper that works like the `HtmlHelper`. So if I did this first:
```
echo $this->Asset->css(['first.css', 'second.css'];
echo $this->Asset->script('some_code.js');
```
Now I want to do this:
```
echo $this->Asset->css(['first.css', 'second.css'];
echo $this->Asset->script('some_code.js');
```
(this is a big difference compared to other plugins. Other plugins need a configuration file where to indicate the files to use for the creation. I hate this)

**What I do not want**
1. when I modify a css or js file, I do not want to worry about having to change anything else (templates or configuration) so that the assets are up to date.


Every change is obviously well accepted. And you can always find other solutions to do the same things ... I'm happy if someone wants to help me make this plugin better :-)

**Pull request closed without merging**
